export const FETCHING_QUERY = 'FETCHING_QUERY';
export const FETCHING_QUERY_SUCCESS = 'FETCHING_QUERY_SUCCESS';
export const FETCHING_QUERY_FAILURE = 'FETCHING_QUERY_FAILURE';
export const UPDATE_QUERY = 'UPDATE_QUERY';